# Copyright (c) 2023 Graphcore Ltd. All rights reserved.
ssf_version: 1.0.0

application:
  id: mnist_api
  name: PopTorch model for MNIST dataset
  desc: MNIST-based trained model API
  version: 1.0
  module: mnist_ssf_app.py
  ipus: 1
  trace: True
  artifacts: ["mnist_datasets_downloaded/**/*", "exe_cache/**/*"]
  max_batch_size: 1

  dependencies:
    python: requirements.txt
    poplar: ["3.2.0"]

  package:
    inclusions: ["mnist_datasets_downloaded/**/*", "exe_cache/**/*"]
    exclusions: []
    baseimage: graphcore/pytorch:3.2.0-ubuntu-20.04

endpoints:

  - id: mnist_api
    version: 1
    desc: Simple application interface for MNIST trained model
    custom: ~

    inputs:

      - id: digit_bin
        type: TempFile
        desc: "Single digit image in any PIL-supported format"

    outputs:

      - id: result
        type: Integer
        desc: "Integer representing predicted digit"
