# Copyright (c) 2023 Graphcore Ltd. All rights reserved.
ssf_version: 1.0.0

application:
  id: sd2_api
  name: Stable Diffusion 2 API
  desc: Stable Diffusion 2 (Text to Image 512x512) API
  version: 1.0
  license_name: CreativeML Open RAIL++-M License
  license_url: https://huggingface.co/stabilityai/stable-diffusion-2/blob/main/LICENSE-MODEL
  module: sd2_ssf_app.py
  ipus: 4
  trace: True
  artifacts: ["weights.onnx", "./model_cache"]
  max_batch_size: 1
  startup_timeout: 3000

  dependencies:
    python: requirements.txt
    poplar: ["3.2.0"]

  package:
    inclusions: ["./exe_cache/*"]
    exclusions: []
    baseimage: graphcore/pytorch:3.2.0-ubuntu-20.04

endpoints:

  - id: txt2img_512
    version: 1
    desc: Simple application interface for Stable Diffusion 2 text-to-image
    custom: ~

    inputs:

      - id: prompt
        type: String
        desc: Image description text prompt

      - id: random_seed
        type: Integer
        desc: Random seed for image generation

      - id: guidance_scale
        type: Float
        desc: Guidance scale for image generation to strongly or weakly match prompt.

      - id: num_inference_steps
        type: Integer
        desc: Number of steps for image generation - higher steps improves image quality.

      - id: negative_prompt
        type: String
        desc: Negative text prompt for image description - include features NOT wanted in generated image.

    outputs:

      - id: result
        type: PngImageBytes
        desc: Generated image output as raw binary
