# Copyright (c) 2023 Graphcore Ltd. All rights reserved.
ssf_version: 1.0.0

application:
  id: simple-batching-test
  name: Test API
  desc: A very simple batching enabled application
  version: 1.0
  module: my_application.py
  trace: True
  artifacts: []
  max_batch_size: 4

  dependencies:
    python: ~

  package:
    inclusions: []
    exclusions: []

endpoints:

  - id: Test1
    version: 1
    desc: This is my simple application interface
    custom: ~

    inputs:

      - id: x
        type: Integer
        desc: An integer value
        example: 100

    outputs:

      - id: requests
        type: Integer
        desc: Count of requests

      - id: x_times_1000
        type: Integer
        desc: Input value x times 1000
