# Copyright (c) 2023 Graphcore Ltd. All rights reserved.
ssf_version: 1.0.0

application:
  id: simple-test
  name: Test API
  desc: A very simple test API
  version: 1.0
  module: my_application.py
  ipus: 0
  trace: True

endpoints:

  - id: Test1
    version: 1
    desc: This is my simple application interface

    inputs:

      - id: x
        type: Integer
        desc: An integer value
        example: 101

    outputs:

      - id: requests
        type: Integer
        desc: Count of requests

      - id: x_times_1000
        type: Integer
        desc: Input value x times 1000

  - id: Test1
    version: 2
    desc: This is a newer version of my simple application interface

    inputs:

      - id: x
        type: Integer
        desc: An integer value

    outputs:

      - id: requests
        type: Integer
        desc: Count of requests

      - id: x_times_1000
        type: Integer
        desc: Input value x times 1000


  - id: TestQuery
    version: 1
    desc: This is a query based version of my simple application interface
    http_param_format: query

    inputs:

      - id: x
        type: Integer
        desc: An integer value
        example: 102

    outputs:

      - id: requests
        type: Integer
        desc: Count of requests

      - id: x_times_1000
        type: Integer
        desc: Input value x times 1000
